### PR TITLE
React stubs for the graph view

### PR DESCRIPTION
**Pull request by wking**
Collapsed cards (#9) and DepIndicators (#10).  Also includes enough of
a scaffold to see that those work (#3).  Also still needs something
like graphviz to position the cards and draw connections, but I
haven't figured out how to work that into the React approach yet.

### CODE REVIEW

**Comment by wking** [comment]
Build is [here][1] if you want to look without building locally.

[1]: https://wking.github.io/depviz/

**Comment by jbenet** [comment]
@wking oh wow! you started on this-- sorry i didnt notice, i just started on it too. will take a look

**Comment by jbenet** [comment]
@wking nice gitlab icons :)

**Comment by wking** [comment]
I wasn't sure if I'd be able to get anything productive done ;).

**Comment by wking** [comment]
Also not sure who this icon is:


unknown-icon

**Comment by jbenet** [comment]
sorry for duplicating work-- https://github.com/jbenet/depviz/tree/master/webapp how do we want to proceed? merge our approaches? take a look at mine so far. i think yours is more advanced

**Comment by jbenet** [comment]
@wking that's Asana. was an example-- doesn't have to be in v0

**Comment by jbenet** [comment]
I moved my work onto a branch: `jbenet-webapp` as i think yours is a better route to go. i can work on the colors/alignment, etc later). let's maybe get the graphviz layout stuff working first, as how we do that will determine whether we use d3 or not, etc

**Comment by wking** [comment]
I just pushed some very preliminary graphviz stuff with 2929916.

**Comment by wking** [comment]
Rerolled a bit, and now you can [shift the `viewBox` around by dragging with a mouse][1].

[1]: https://wking.github.io/depviz/

**Comment by jbenet** [comment]
> https://wking.github.io/depviz/

- that's great!
- make it the whole screen? i'll play with the colors tonight. 
- are the lines drawn from graphvis or did you connect them separately?

**Comment by jbenet** [comment]
> https://wking.github.io/depviz/

- that's great!
- make it the whole screen? i'll play with the colors tonight. 
- are the lines drawn from graphvis or did you connect them separately?
- we can probably use graphviz to draw the graph (with bended edges to minimize crossings + small arrows) and replace the svg elems or just paste ours on top

**Comment by jbenet** [comment]
This is taking shape!!! great stuff, @wking 

Progress screenshot for those following. Yes, that's real data. 👍 

2016-11-23 at 9 23 pm

**Comment by jbenet** [comment]
saw latest, some notes:

- nice home page! nice text field, to search for issues, it works! \o/
- text-field for link should be on the black bar (a bit like quora) so can easily navigate to another
- when using the proper link (long, full unique id), should use `/http/github.com/jbenet/depviz/issues/1` (instead of `/http/github.com/jbenet/depviz/1`)
- the top circle should turn red when its dependencies are not done yet (right now it shows it green).
- the bottom circle should turn green once the issue is done
- responsiveness: the canvas view port should resize when resizing the page, particularly to a larger window size

**Comment by wking** [comment]
On Fri, Nov 25, 2016 at 10:42:18PM -0800, Juan Benet wrote:
> - text-field for link should be on the black bar (a bit like quora)
>   so can easily navigate to another

+1, will do this soon.

> - when using the proper link (long, full unique id), should use
>   `/http/github.com/jbenet/depviz/issues/1` (instead of
>   `/http/github.com/jbenet/depviz/1`)

I don't think we need our URLs to distinguish issues/PRs.  We just
need to support redirects from the longer forms to help with
copy/paste (and this PR currently does that).  More on this in #4 and
#5.

> - the top circle should turn red when its dependencies are not done
>   yet (right now it shows it green).
> - the bottom circle should turn green once the issue is done

I'd thought I had these handled appropriately.  Will double check.

> - responsiveness: the canvas view port should resize when resizing
>   the page, particularly to a larger window size

Done just recently (pushed to gh-pages on 23:12-0800).  Try again?

**Comment by wking** [comment]
On Fri, Nov 25, 2016 at 10:42:18PM -0800, Juan Benet wrote:
> - the top circle should turn red when its dependencies are not done
>   yet (right now it shows it green).

Fixed with 9acd8d5.

> - the bottom circle should turn green once the issue is done

This seems to be working [1], although the logic I'm using colors it
neutral if there are no deps, and red/green depending on done-ness if
there are deps [2].  This differs from the logic you lay out in #10
but matches your mock from #9 (notes in 7c69b7d).

[1]: https://wking.github.io/depviz/#/http/dummy/jbenet/depviz
[2]: https://github.com/wking/depviz/blob/9acd8d5af3c3c9f7e58ff537228dc5d32fc62bce/webapp/src/DepIndicators.js#L47-L50

**Comment by jbenet** [comment]
thanks @wking ! I'm going to merge this, so that others can see the latest easily and contribute too. I'll also try to close some issues, or ask in them, if they're done.

**Pull request merged**
