### PR TITLE
DepIndicators: Add pie-chart completion to the dependencies indicator

### LINKED ISSUE #12: Idea: make the dependency number circle change from red to green as dependeencies are fulfilled.
Example:
bubble

---

depends on #38

### PR DESCRIPTION
**Pull request by wking**
Also change the number to white, matching the mocks.  Bold the number and darken the other colors to make the white numbers more visible.

Fixes #12.

### CODE REVIEW

**Comment by wking** [comment]
Screenshots of the new indicator:

pie

pie-2

**Comment by jbenet** [comment]
super nice!

**Comment by jbenet** [comment]
@wking is this ready for merging? it LGTM.

**Comment by wking** [comment]
On Thu, Dec 01, 2016 at 03:25:14PM -0800, Juan Benet wrote:
> @wking is this ready for merging? it LGTM. 

Yup, merge whenever (I'll put WIP prefixes on PRs that I think are not
ready).

**Pull request merged**
