### PR TITLE
DepCard: Expanded cards

### LINKED ISSUE #8: ExpandedDepCardView
This is the view of an _expanded card_.

It must have:
- [ ] An "ID" segment (website logo + local shorthand identifier)
- [ ] A Title
- [ ] Labels, if any
- [ ] People, if any (assignees on github)
- [ ] Comments/Notes count, if any
- [ ] Progress count, if any (checkbox, based on issue checkboxes)
- [ ] Progress bar, if any (same count, just rendered as the background filling up the bar.
- [ ] 3 Dependency Indicators (dependencies, related, dependents)
- [ ] Edge should change color depending on whether it's done (green) or not (red).

---

The center thing on:

---

depends on #34
depends on #35

### PR DESCRIPTION
**Pull request by wking**
There's currently no way to toggle between collapsed/expanded, or label buttons, comment counts, task counts, or assignee icons.  But this is where I am at the moment ;).  I thought I'd push it to avoid duplicating effort.

Fixes #8.

### CODE REVIEW

**Comment by jbenet** [comment]
i think travis wants more coverage

**Comment by wking** [comment]
Yeah, this is very work-in-progress.  I'll remove the WIP prefix when I think it ready.

**Comment by jbenet** [comment]
Ah-- got it.

**Comment by wking** [comment]
Still a few cases that aren't handled well (long titles, multiple assignees, adjusting the graph layout depending on node size, a UI for toggling expanded-ness), but the commit I just pushed to this PR handles the core expanded-node features:

expanded

I put the person icon in the upper right since the host icon is in the top line, and having both icons in the same line makes line spacing more consistent when the image height is different from the usual line spacing.

The comment, task, and default-avatar icons use Unicode, so you'll need a font that supports the code points I'm using.  Details on that in the commit message.

**Comment by wking** [comment]
I've added `e` and `c` hotkeys to toggle expanded/collapsed.  There are some caveats to this approach (details in the commit message, especially the fact that you need to focus on the SVG-wrapping div before we notice your keypresses), but I think it's good enough for this to be merge-able.

**Comment by wking** [comment]
Fixed a GitHub-mock default with 8680c8a → 7f5536d to get tests passing again.

**Comment by jbenet** [comment]
Great! looking good-- let's merge this

**Comment by wking** [comment]
For some reason, expand/collapse replace calls don't seem to be triggering a re-render, although that had been working in my local testing earlier.  I'll go through my reflog and see where that broke…

**Comment by wking** [comment]
On Thu, Dec 01, 2016 at 05:50:39PM -0800, W. Trevor King wrote:
> For some reason, expand/collapse replace calls don't seem to be
> triggering a re-render…

They seem to be working now.  Maybe I'd just forgotten to focus on the
graph first [1].

[1]: https://github.com/jbenet/depviz/pull/35#issuecomment-264118263

**Pull request merged**
