### PR TITLE
Home: Set overflow-y to auto for scrolling on small windows

### PR DESCRIPTION
**Pull request by wking**
For example, my cell phone screen is not big enough to see the whole intro.  There's a bit of shuffling around to set an explicit height and width, without which Firefox doesn't seem to want to set the scrollbar.

### CODE REVIEW

**Comment by wking** [comment]
Pushed fd18956 → 98ef1b8 with a coverage fix.

**Comment by jbenet** [comment]
I think a merge caused a conflict

**Comment by wking** [comment]
I'll rebase tonight.

**Comment by wking** [comment]
Rebased onto master with 98ef1b8 → 07f3086.

**Pull request merged**
